### ISSUE TITLE
Aanpassingen aan ajax call

### ISSUE THREAD

**Issue by GlennVL91** [Tactics/FormGoodnessBundle#4]
Bij ons werkt enkel "type" ipv "method" weet niet of dat aan jquery versie ligt of niet en of dit dan oplosbaar is of niet.

Ook lukt die request_data enkel met POST 'method' ('type'). Zou oplossing zijn als je dit zou kunnen meegeven of als je POST gebruikt indien er request_data is meegegeven.

**Comment by aaronmu** [comment]
@GlennVL91 

Is dit nog van toepassing?
Welke jQuery versie gebruik je?
Vraag twee snap ik niet goed.
